version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017