spring:
  data:
    mongodb:
      #host: mongodb
      #port: 27017
      #database: vehicle
      uri: mongodb://localhost:27017/vehicle
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework: ERROR
    io:
      app: TRACE